### ISSUE TITLE
Adding into NAT setup

### ISSUE THREAD

**Issue by IngwiePhoenix** [iAmGhost/VitaUpdateBlocker#10]
hey.

I am connecting to the internet through a RasPi running a properly configured dnsmasq and iptables, allowing me to pass through. The ideao f this was to bypass a school ruling that'd only allow one MAC address to be registered with the router. Through the NAT, I can connect all devices through a single MAC address with another AP on the other end.

```
Dorm router <- Wifi Dongle <- Raspberry Pi -> AP -> Devices (PS3, 4, V, TV, ...)
```

Since my devices already pass through this RasPi, do I still need to apply the proxy settings or am I right to assume that iptables passes traffic from `eth0` straight to `wlan0` without any pre-/postprocessing?

Kind regards, Ingwie!

**Comment by iAmGhost** [comment]
I think this is unrelated with VitaUpdateBlocker.

By the way, if dorm router allows only one MAC, isn't it connecting wireless router to dorm router is enough?

**Comment by IngwiePhoenix** [comment]
Well, I decided to just go the manual route, and launch the proxy on a port on the gateway.

And no, not really. Connecting my AirportExtreme access point to the dorm router would not work since it would join the network and repeating it, would mean that the MAC addressed woudl be sent to the dorm router, which would deny authentification. So I just use a NAT and i am good to go.

Thanks for your answer!
