### ISSUE TITLE
Suddenly decided to stop functioning.

### ISSUE THREAD

**Issue by IngwiePhoenix** [iAmGhost/VitaUpdateBlocker#14]
It turns out that basically out of nowhere, the Proxy stopped working.

I've ran the proxy on my RasPi since forever now, and I just came bakc from vacation, turned the Vita TV on and had forgotten to start the proxy first, sicne it wasn't in my init.d-scripts.

So now I am greeted with an update question every now and then...

I tried to rebase my database but to no avail. What other things can I do to make the PS TV "forget" that there is an update?

Kind regards, Ingwie.

**Comment by IngwiePhoenix** [comment]
I just did some further research. Although you fetch the request and replace it...the Vita TV still picks up the new version anyway. So maybe the XML got changed? o.o

I am no good in reverse engeneering connections since I have no software to sniff out the Vita TV's HTTP/S traffic.

**Comment by iAmGhost** [comment]
This is well known behavior and it's server side blocking(maybe Sony is deprecating old certificates?) there's nothing can I do.

**Comment by IngwiePhoenix** [comment]
I see. That sucks. I'll have to see how to get games on it, then :)
But thanks for your response anyway! ^.^
