### ISSUE TITLE
Unable to get it running under Ubuntu 14.04

### ISSUE THREAD

**Issue by SpasilliumNexus** [iAmGhost/VitaUpdateBlocker#4]
I've installed mitmproxy, but every time I run "python vita_update_blocker.py" I get this error:

[Thu Jan 22 05:41:08 2015] Listening on 192.168.1.100:8080
[Thu Jan 22 05:41:08 2015] Blocking non-related traffic is DISABLED.
Traceback (most recent call last):
  File "vita_update_blocker.py", line 132, in <module>
    main()
  File "vita_update_blocker.py", line 125, in main
    cacert=os.path.expanduser("~/.mitmproxy/mitmproxy-ca.pem")
TypeError: __init__() got an unexpected keyword argument 'cacert'

I've updated pip and python (not python3) in hopes of fixing it with no success. I'm at a loss of what's missing.

**Comment by iAmGhost** [comment]
I was too lazy to specifiy working mitmproxy version: I think something is changed in new version.

And I'm lazy for creating Ubuntu environment for testing too, can you test if this version is working?
https://gist.github.com/iAmGhost/b67c9b398e08b95c556f

**Comment by SpasilliumNexus** [comment]
Hey again,
I just tested the new version and this time it gives a different error

[Thu Jan 22 12:08:44 2015] Listening on 192.168.1.100:8080
[Thu Jan 22 12:08:44 2015] Blocking non-related traffic is DISABLED.
Traceback (most recent call last):
  File "vitae.py", line 130, in <module>
    main()
  File "vitae.py", line 125, in main
    server = proxy.ProxyServer(config)
AttributeError: 'module' object has no attribute 'ProxyServer'

I've Googled "ProxyServer" and "module", and was able to pip install module, but that didn't help.
If this helps in any way, using mitmproxy --version in Terminal returns "mitmproxy 0.11.3"

**Comment by iAmGhost** [comment]
Sorry for bad fix, I don't have time to make proper fix for latest mitmproxy.
Forget new version and try installing older mitmproxy with this command:
pip install mitmproxy==0.8
or 0.8.1 or 0.10

**Comment by iAmGhost** [comment]
fixed in 5e821ce2082a67a543bfedc9eeeffe8066999eee
