### ISSUE TITLE
Spoofs vita's real version instead of latest version randomly.

### ISSUE THREAD

**Issue by 133794m3r** [iAmGhost/VitaUpdateBlocker#8]

**Comment by 133794m3r** [comment]
As it says on the tin, it says spoofing it spoofs vita's versioin and half ofthe time it doesn't work at all.

heres the logs.
[Mon Jun 29 17:07:41 2015] Listening on 192.168.0.184:8080
[Mon Jun 29 17:07:41 2015] Blocking non-related traffic is ENABLED.
[Mon Jun 29 17:07:56 2015] Vita's real version is: 03.510.000
[Mon Jun 29 17:07:56 2015] latest version is: 03.520.000
fixme:toolhelp:CreateToolhelp32Snapshot Unimplemented: heap list snapshot
fixme:toolhelp:Heap32ListFirst : stub
[Mon Jun 29 17:07:56 2015] Spoofed latest version to 03.510.000.
[Mon Jun 29 17:07:56 2015] You can disable proxy settings now.
[Mon Jun 29 17:08:17 2015] Vita's real version is: 03.510.000
[Mon Jun 29 17:08:18 2015] latest version is: 03.520.000
[Mon Jun 29 17:08:18 2015] Spoofed latest version to 03.510.000.
[Mon Jun 29 17:08:18 2015] You can disable proxy settings now.
[Mon Jun 29 17:08:36 2015] Vita's real version is: 03.510.000
[Mon Jun 29 17:08:36 2015] latest version is: 03.520.000
[Mon Jun 29 17:08:36 2015] Spoofed latest version to 03.510.000.
[Mon Jun 29 17:08:36 2015] You can disable proxy settings now.
[Mon Jun 29 17:09:04 2015] Vita's real version is: 03.510.000
[Mon Jun 29 17:09:04 2015] latest version is: 03.520.000
[Mon Jun 29 17:09:04 2015] Spoofed latest version to 03.510.000.
[Mon Jun 29 17:09:04 2015] You can disable proxy settings now.
[Mon Jun 29 17:09:12 2015] Vita's real version is: 03.510.000
[Mon Jun 29 17:09:12 2015] latest version is: 03.520.000
[Mon Jun 29 17:09:12 2015] Spoofed latest version to 03.510.000.
[Mon Jun 29 17:09:12 2015] You can disable proxy settings now.
[Mon Jun 29 17:10:57 2015] Vita's real version is: 03.510.000
[Mon Jun 29 17:10:57 2015] latest version is: 03.520.000
[Mon Jun 29 17:10:57 2015] Vita's real version is: 03.510.000
[Mon Jun 29 17:10:58 2015] latest version is: 03.520.000
[Mon Jun 29 17:10:58 2015] Spoofed latest version to 03.510.000.
[Mon Jun 29 17:10:58 2015] You can disable proxy settings now.
[Mon Jun 29 17:10:58 2015] Spoofed latest version to 03.510.000.
[Mon Jun 29 17:10:58 2015] You can disable proxy settings now.
[Mon Jun 29 17:14:02 2015] Vita's real version is: 03.510.000
[Mon Jun 29 17:14:02 2015] latest version is: 03.520.000
[Mon Jun 29 17:14:02 2015] Vita's real version is: 03.510.000
[Mon Jun 29 17:14:02 2015] latest version is: 03.520.000
[Mon Jun 29 17:14:02 2015] Spoofed latest version to 03.510.000.
[Mon Jun 29 17:14:02 2015] You can disable proxy settings now.
[Mon Jun 29 17:14:02 2015] Spoofed latest version to 03.510.000.
[Mon Jun 29 17:14:02 2015] You can disable proxy settings now.
[Mon Jun 29 17:14:21 2015] Vita's real version is: 03.510.000
[Mon Jun 29 17:14:21 2015] latest version is: 03.520.000


No idea wy this is happeing ut it's annoying as I don't have any real option outside of this. I'm using the windows binary as mitmproxy is too knew for my distro with the python script.

**Comment by 133794m3r** [comment]
I shoul also say that when it works it ays "spoofed 3.510.00" even though that _shouldn't_ work. It does andthe it lets me into psn, bu any online games it doesn't work.

**Comment by iAmGhost** [comment]
It's normal behavior, have to spoof latest version to match your Vita's version so your device will think it's on latest version.
